project:
  type: website

website:
  title: "repliMAT blog"
  site-url: https://reproducibleMATLAB.github.io/blog
  description: "Research reproducibility with MATLAB"
  navbar:
    right:
      - about.qmd
      - text: repliMAT
        href: https://reproducibleMATLAB.github.io
        target: _blank
      - icon: github
        href: https://github.com/reproducibleMATLAB/blog
        target: _blank
      - icon: rss
        href: index.xml
format:
  html:
    from: markdown+emoji
    theme: 
      light: litera
      dark: [litera, theme-dark.scss]
